from app.crud.users import (
    authenticate,
    create_user,
    create_user_with_employee,
    delete_user_and_employee,
    get_all_users_with_roles,
    get_user_by_email,
    get_user_profile,
    get_users,
    update_employee_role,
    update_user,
    DUMMY_HASH,
)
from app.crud.projects import (
    build_project_summaries,
    count_active_projects,
    count_completed_projects,
    get_all_active_projects,
    get_delayed_projects,
    get_project_manager,
    month_bounds,
    prev_month,
    sum_invoices,
    get_or_create_client,
    create_project,
    get_project_by_job_number,
    get_project_by_id,
    get_all_projects,
    build_project_details,
    get_projects_by_status,
    delete_project,
    update_project,
)

from app.crud.project_statuses import (
    get_status_type,
    create_status_type,
)

__all__ = [
    # users
    "authenticate",
    "create_user",
    "create_user_with_employee",
    "delete_user_and_employee",
    "get_all_users_with_roles",
    "get_user_by_email",
    "get_user_profile",
    "get_users",
    "update_employee_role",
    "update_user",
    "DUMMY_HASH",
    # projects
    "build_project_summaries",
    "count_active_projects",
    "count_completed_projects",
    "get_all_active_projects",
    "get_delayed_projects",
    "get_project_manager",
    "month_bounds",
    "prev_month",
    "sum_invoices",
    "get_or_create_client",
    "create_project",
    "get_project_by_job_number",
    "get_project_by_id",
    "get_all_projects",
    "build_project_details",
    "get_projects_by_status",
    "delete_project",
    "update_project",
    # project statuses
    "get_status_type",
    "create_status_type",
]
